    

checkout([$class: 'GitSCM', 
    branches: [[name: 'https://github.com/nirmaltest07/nirvana_8thJuly19']],
    doGenerateSubmoduleConfigurations: false,
    extensions: [
        [$class: 'SparseCheckoutPaths',  sparseCheckoutPaths:[[$class:'SparseCheckoutPath', path:'https://github.com/nirmaltest07/nirvana_8thJuly19/nirwanaWeb']]]
                ],
   
