node{
  stage('SCM Checkout') {
    git 'https://github.com/nirmaltest07/nirvana_8thJuly19'
    }
    stage('Compile-Package'){
    def mvnHome = tool name: 'Maven 3.6.1', type: 'maven'
      sh "${mvnHome}/bin/mvn package"
    }
}
   
